//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Documento
{
    private string nombre;
    private string texto;
    private IPicturAble oPictureProxy;

    public Documento(String nombre)
    {
        this.nombre = nombre;
        CargarContenido();
        MostrarContenido();
    }

    public virtual string Nombre
	{
        get
        {
            return nombre;
        }
        set
        {
            nombre = value;
        }
	}

	public virtual string Texto
	{
        get
        {
            return texto;
        }
        set
        {
            texto = value;
        }
	}

	public virtual IPicturAble IPicturAble
	{
        get
        {
            return oPictureProxy;
        }
        set
        {
            oPictureProxy = value;
        }
	}

	public void CargarContenido()
	{
        texto = "Texto del documento";
        oPictureProxy = new ProxyPicture("imagen.jpg");

        Console.WriteLine("Objeto cargado en memoria");
    }

    public void MostrarContenido()
	{
        Console.WriteLine("Mostrando Contenido...");
    }

    public void hacerScroll()
    {
        Console.WriteLine("El usuario hizo scroll");
        oPictureProxy.MostrarImagen();
    }

}

