//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class RealPicture : IPicturAble
{
    private string nombre;

    public RealPicture(string nombre)
    {
        this.nombre = nombre;
    }
    

    public void MostrarImagen()
    {
        Console.WriteLine("Mostrando imagen " + nombre + " ...");
    }

}

